### ISSUE TITLE
Connecting two transmons by an inductor works but not with a capacitor

### ISSUE THREAD

**Issue by marekgluza** [stanfordLINQS/SQcircuit#17]
Hi, coupling two transmons via a capacitor doesn't work but with an inductor it works. If I switch of specifying loops on each of the tuneable transmons then it works again.

The error message is: 
LinAlgError: Last 2 dimensions of the array must be square

Here an example of what I tried so far

![Capacitative coupling of two transmons(2)](https://user-images.githubusercontent.com/6939096/210505935-1198d120-5f2d-42bf-abf6-143ca9a516fe.png)

The code is fun, thanks!

**Comment by marekgluza** [comment]
I read a previous issue response @taha1373 in https://github.com/stanfordLINQS/SQcircuit/issues/2#issuecomment-1164886741_
and 'grounding' each transmon indeed works
![Capacitative coupling of two transmons-Copy1](https://user-images.githubusercontent.com/6939096/210506996-99570e88-fa3e-4447-8cd2-03a35e8f86fe.png)

**Comment by taha1373** [comment]
Hi @marekgluza,

Thank you for using SQcircuit and for taking the time to report the issue. I'm glad that were able to resolve it! If you have any further questions or encounter any other issues, please don't hesitate to reach out.
