### ISSUE TITLE
The order of the elements in the circuit description matters

### ISSUE THREAD

**Issue by GabrielJauma** [stanfordLINQS/SQcircuit#19]
As you can see in the screenshots, changing the order in which the inductor and capacitor are listed changes the resulting circuit.

![image](https://github.com/stanfordLINQS/SQcircuit/assets/83074925/d934a9a9-afc3-4af0-989c-e47399136b87)
![image](https://github.com/stanfordLINQS/SQcircuit/assets/83074925/7191a30a-c0fa-4000-8caf-478aabeb87c1)

Anyways, thanks a lot for this code, it is great! Keep it up =)

**Comment by GabrielJauma** [comment]
Okay, I think I now understand why this is happening. I believe that I should have introduced both the capacitor and the inductor in a single line of code, that is, as a single entrance to the dictionary. 

Maybe you could include a warning saying that all the elements between two nodes should be included in the same line?

Have a great one =)

**Comment by taha1373** [comment]
Thank you, @GabrielJauma, for using SQcircuit and for sharing your issue with us. I appreciate your feedback and will work on adding the requested feature to SQcircuit in the near future. Thanks again for helping us improve!
